### ISSUE TITLE
Merge !bankboard and !cashboard

### ISSUE THREAD

**Issue by idunnoooooo** [PixelSized/DBM-Economy-Remastered#4]
can u Merge !bankboard and !cashboard commands? i tried but without success :/

**Comment by PixelSized** [comment]
Wdym???
they are 2 seperate commands, one shows highest bank, one shows highest cash

**Comment by idunnoooooo** [comment]
@PixelSized i mean, one command that will show bank and cash total.

**Comment by PixelSized** [comment]
Ah, this can be done by merging the 2 actions together

**Comment by idunnoooooo** [comment]
@PixelSized thanks. btw cash command isnt working for me for some reason.... no errors in logs i am missing mods or something?

**Comment by PixelSized** [comment]
Possibly, dm me on discord
PixelSized#8008

Show me your action list
