### ISSUE TITLE
Slots Issue

### ISSUE THREAD

**Issue by Notiix** [PixelSized/DBM-Economy-Remastered#5]
When doing the "[p]slots <Amount>" command, the slot message comes up saying "Slot Machine with start in 3 seconds." And then it won't continue. Do I have to change anything in DBM to help make this work?

**Comment by JbOnEJ** [comment]
@KillerModz You probably don't have the edit embed in your game directory and bots directory. Make a .js file and put this into it. Make sure to put it both in your game directory actions folder and your bots. Here's the link for it. (This raw data is old. So this is a outdated mod, so use at your own risk. I am not responsible for nothing damaged or lost.) 

https://github.com/dbm-network/mods/blob/1.9/actions/edit_embed_MOD.js
